name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 2.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.2
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  video_compress: ^3.1.3
  path_provider: ^2.1.5
  intl: ^0.20.1
  path: ^1.9.0
  transparent_image: ^2.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
